### PR TITLE
Allow access to Node.js & Electron APIs in JS code injection

### PR DESCRIPTION
**Pull request by linonetwo**
I will add some usage examples later.

### CODE REVIEW

**Review by quanglam2807 — APPROVED** [review]

**Comment by quanglam2807** [comment]
This Wiki page will be used for documentation: https://github.com/atomery/webcatalog/wiki/JS-Code-Injection. I'll link the app to the wiki page in another PR.

**Comment by insolite** [comment]
@quanglam2807 is there any example coming? I tried that with no luck:
```js
const { app, protocol } = require('electron');
```
It says:

> Cannot find module 'electron'

though the `require` is defined and being called.

The same for `path`, `fs`, etc.

Is that how it is supposed to work?

**Comment by insolite** [comment]
Well, I debugged it a bit. Not sure why but the `require` function is being transpiled into something else than the original `require` (see `r(66)` value). I think that might be somehow related to dynamic importing or security.

image

**Comment by insolite** [comment]
I guess we just can't use `require` dynamically (as much as like `variable = 'electron'; require(variable)`) so it can't be passed as a variable as well.

**Comment by linonetwo** [comment]
I think this injected to preload script, which is where webpage runs, so there is no electron to require.

**Comment by insolite** [comment]
I bet it doesn't depend on the exact module. `path` doesn't work as well. Because the provided `require` value triggers error instantly (see `t = new Error(...` statement).

**Comment by insolite** [comment]
I tried `import('path')` but that makes the page crash
image

Anyway, could you please point out what's the expected electron/node use case then?

**Comment by insolite** [comment]
Well, this works just fine though
image

So might be a minifier issue or a similar build-level issue.

**Comment by insolite** [comment]
So the solution to workaround webpack's replacement might be like this:

Replace the
```js
  )(require)
```
with
```js
  )(eval('require'))
```

at [neutron/main-src/libs/view-preload/index.js#L137](https://github.com/webcatalog/neutron/blob/3944d0f8ca7ab50ada8d4a8fd763805b4c782df9/main-src/libs/view-preload/index.js#L137)

Perhaps there should be an option for that in babel/webpack but I was unable to find it so far.

**Comment by Jorl17** [comment]
Can anyone provide a working example using `electron.app`, please? I am trying to use this functionality but I can't seem to do it.

All I want to do is set the app badge on macOS. I also tried
`window.webcatalog.setBadgeCount(value);` but it blows up.

**Pull request merged**
