### PR TITLE
Detach popup windows from main window

### PR DESCRIPTION
**Pull request by quanglam2807**

### CODE REVIEW

**Comment by jonsnelson** [comment]
Thank you for this!!

**Comment by jonsnelson** [comment]
I just realized that on the Menu Bar is always visible (can't be hidden) on popup windows. (This is the case on other electron apps I've used) Is there a way to hide the Menu Bar by default? (the Alt key doesn't hide it)

**Comment by marcusquinn** [comment]
Although this feature now works in opening windows without a nav bar - nothing loads in that new window for me when cmd-clicking now.

**Comment by marcusquinn** [comment]
eg:

image

**Pull request merged**
