### PR TITLE
Fix swiping confuses between going back and forward

### LINKED ISSUE #644: bug: 2/3 finger swipe to navigate is backwards ?
# Bug Report
**Current Behavior:**

If you enable the swipe to navigate option, I have noticed that you have to swipe forwards to navigate backwards. This is the opposite from Safari and Chrome and is very confusing.

Note: I enabled the use 2 and 3 finger swipe gesture so that I could still use 2 fingers in Chrome - am I right in thinking that WebCatalog only supports 3 fingers? I wish it would support 2 like the browser).

**Expected Behavior:**

I should be able to swipe from right to left to go backwards, and left to right to go forward - however WebCatalog apps seem to do the opposite?

**Steps to Reproduce:**

**Additional Context**

### PR DESCRIPTION
**Pull request by linonetwo**
> Hmmm seems to work as expected now, weird - maybe just a long day @macta

Maybe it just we are confused by this inversed feedback, and our brain adapt to it ( same on me ).

Just like https://www.youtube.com/watch?v=OJTC_E2Nlgg

Resolve #644

### CODE REVIEW

**Comment by quanglam2807** [comment]
Thanks a lot!!! The behavior was wrong right from the beginning but I don't know why nobody reported it.

**Comment by dave-redfern** [comment]
I think this fix has actually broken the three finger swiping. 3-fingers left should go back, 3 fingers right should go forward. This is how it is implemented in macOS (check in the TrackPad options video overview, Safari, Chrome, Opera etc). This was working correctly before this change.

FYI I use these gestures all the time for inter page back/forward, so this for me is a major PITA 😢

**Comment by macta** [comment]
Didn’t you mean to say “swiping from the left of the trackpad to the right" - so a right swipe is backwards? This is what the Trackpad options video shows (so I agree that this is the best description) - its also how it works in Safari to go backwards too.

**Comment by macta** [comment]
By the way - I disagree that it worked properly before this change - it was random, sometimes going in either direction and sometimes not working at all (my main test case was the BBC website, but it also others exhibited the same) - something was/is very strange with this.

**Comment by dave-redfern** [comment]
I meant: if you swipe left i.e. you start at the right side of the trackpad and move towards the left side, this should be the back gesture. If you start from the left side and swipe towards the right it's a forward gesture. That is what happens in Safari (just tried it), Opera et al. I'm not aware of any other modifiers to change this behaviour (nothing in the trackpad app to change it at least).

I've not had issues previously (except when gestures weren't working at all, except on the title bar). I do know that if a site responds slowly due to poor JS event handling, the page can stutter potentially affecting the gestures (Atlassian Jira / Confluence are prone to that). Only fix there is waiting for the page to finish loading.

**Comment by linonetwo** [comment]
@dave-redfern I tested this in the safari, and I agree with you...
Seems three-finger swiping is the inversed version of two-finger swiping.


I was changing this to mimic two-finger gestures, and I've never used three fingers to navigate before. Sorry for this inconvenience for you.

@macta I think our confusion is similar to that "Upside Down Glasses Challenge", maybe we are used to that two-finger gesture, so our brain confused?

**Comment by dave-redfern** [comment]
@linonetwo To be fair the three finger swiping is not the default. IIRC it's usually assigned to a 4-finger swipe; the option is "Swipe between pages".

**Comment by quanglam2807** [comment]
Thanks a lot for the discussion, everyone. As discussed, I'll revert this PR for now. As Electron doesn't support `swipe` event well, probably to resolve this issue altogether, we'll need to rely on JS library. http://jofan.github.io/Touchy/

**Comment by macta** [comment]
Hi - this isn’t normal OS X behaviours - when you write: “ if you swipe left i.e. you start at the right side of the trackpad and move towards the left side” , that’s inverted behaviour - what you describe is considered a forward scroll. 

In OS X it normally follows iPhone behaviour , and it’s based on the idea that you are “grabbing” the page and pulling it left, hence that’s a forward operation.

My preferences video shows it this way - unless you have opted to invert all the actions.

To check this - how do you scroll down with touchpad? Do you pull down from the top to the bottom? If not - you’ve inverted it to match Windows (traditionally the mac and Windows do this opposite ways unless you toggle a setting - but toggling that’s setting is not normal OSX behaviour).

I don’t think it would be easy for an electron app to follow the settings preference (maybe?)  hence hard coding the default might be the only option (but in this case - I think @dave, you will be unhappy as you have inverted the default).

I prefer the default setting which is the more physical iPhone behaviour.

All this said - it hasn't consistent before, And seemed to get muddled up.

I haven’t tried it on the latest build - as I didn’t realise it was released. Before updating my copy, I’ll give it a spin and report back, but I suspect it’s difficult to get right.

**Comment by dave-redfern** [comment]
@macta I am finding this conversation fascinating! It's interesting to see other peoples points of view / UX expectations.

For scrolling I use the "Natural" scrolling option where the content tracks finger movement. From a little searching, apparently this option was introduced in 2011 and was also made the default (and there were loads of posts about scrolling being broken when it was made 😀). I happen to prefer this... but then I'm one of those weird people that _has_ to invert y-controls in games to be like a flight sim.

I then went looking more into the option "Swipe between pages", and from everything I've found points to page navigation on _macOS_ specifically having always been: left is previous, right is next. It's even that way on [Apples support document](https://support.apple.com/en-ca/HT204895) where the text description is:
> Swipe between pages
> Swipe left or right with two fingers to show the previous or next page.

Not a great sentence, but I interpret this as: "swipe left" is "previous" and "swipe right" is "next". Incidentally, and actually quite a surprise to me: I have no difficulty with these actions being different between iOS and macOS. Maybe because on iOS you have to start at the edge of the screen? (since right side 2 finger, edge swipe is notifications on macOS) Weird eh?!

At any rate: since you can detect the swipe direction, would it be possible to make it an option? e.g.: "Swipe left gesture: [X] previous page || [] next page" and then default to whatever you feel is appropriate 😉

**Comment by macta** [comment]
You are right, this is interesting… but I’m confused as I also have the “natural” scrolling option enabled? In safari (lets use it as an example as its a native browser), if you want to scroll to the bottom of a page, you use 2 finger swipe from the bottom to the top - thus you are “pulling” the page up like you would on an iPhone right? (This is what natural does on my MacBook - and I believe this is the default?).

By the same token - in safari, on bbb.co.uk, if I go to the home page and then click on a link - I pull the page right to go back (so swipe from left to right) - but it sounds like you have natural up down movement but not natural left right? My laptop has always been this way, so I’m surprised you see different (and I’ve used other users laptops, and there’s all work this way too).

Going back to Webcatalog - build 8.4.0 seems to work how you describe - and there is perhaps where the confusion lies - the left/rigth swipes work how you describe but not how the native safari works in the default natural state. Of course, given a user can enable/disable this setting - its a tough one to get right - but I would think that for most people (unless my laptop and others in the UK, are all backwards by default) they would be confused like me.

**Comment by quanglam2807** [comment]
Thanks everyone for the discussion. I've reverted this change in the last update.

Also, I have looked around and here is what I come up with.

The "Swipe between pages" gesture has 3 options:
> **A**) Scroll left or right with two fingers **B**) Swipe left or right with three fingers **C**) Swipe with two or three fingers
> **Option A** is the new navigation method featured in the new Safari during the WWDC keynote. It is the new feature in Lion. You SCROLL left to go FORWARD, right to go BACKWARD. You get the cool page flipping effect with this but developers need to update their code to support this feature.
> **Option B** is the original swipe to navigate method used in Snow Leopard after the introduction of the Magic Touch Pad. You SWIPE left to go BACKWARD, right to go FORWARD. Many cool apps support this feature only at this stage.
> **Option C** is the best of both world. Try to use it and play around in the new Safari... it is a bit confusing to navigate with both 2 fingers and 3 fingers swipes in the opposite directions :p
> https://apple.stackexchange.com/a/16904

At the moment, because of limitation of Electron API (https://github.com/electron/electron/issues/2683), only Option B & Option C (three-finger swipe) are supported by WebCatalog + Singlebox. The good thing is that Option C would allow you to use both A & B at the same time. 

As mentioned above (and also in Electron documentation), they are legacy behaviors and use different direction from Option A. It's quite confusing so I'll try to make it clearer in the app UI.

Option B & C are strange but they're Mac's default behavior so I wouldn't do anything differently for now. Hopefully, Electron will add support for Option A in the near future (the swiping event is currently handled natively through Electron API). 

But probably, it's possible to add support for Option A through other means. Still, there needs to be a way to access the Trackpad system preferences so the app can handle the gestures correctly on its own.

If you guys have any additional points to add, feel free to! I'll create a new issue for this so we can move the discussion there.

## References:
https://apple.stackexchange.com/questions/16896/how-can-i-swipe-with-three-fingers-to-go-back-and-forth-in-my-history-while-brows/16904#16904

https://apple.stackexchange.com/questions/21410/why-does-three-finger-swipe-gesture-not-support-natural-scrolling

https://github.com/electron/electron/issues/2683

https://www.electronjs.org/docs/api/browser-window
Screen Shot 2020-04-29 at 3 50 20 PM

**Pull request merged**
