### PR TITLE
Add ability to create/install context apps

### PR DESCRIPTION
**Pull request by quanglam2807**

### CODE REVIEW

**Comment by grumphus** [comment]
What are context apps? Thanks!

**Comment by quanglam2807** [comment]
@grumphus Thanks for asking! The feature will be available widely soon.

> Context apps, such as Work, School, and Life, are special apps that are not tied to any specific web apps/websites. They let you run multiple web apps in a single well-organized window as independent workspaces which you can switch between easily using keyboard shortcuts. Each workspace is sandboxed, protecting you from cross-website trackers and preserving your privacy.

> If you are familiar with Singlebox app, another product from Atomery, in fact, each context app works similarly to an independent Singlebox instance.

**Comment by grumphus** [comment]
Interesting. Looking forward to seeing some examples soon. Thanks for your continued development and support!

**Comment by quanglam2807** [comment]
@grumphus Thank you so much! The feature is now available in v22.3.0. Please give it a try and let me know what you think.

**Comment by grumphus** [comment]
Nice. How do I test it? I still don't quite understand what Work, School and Life apps are.

**Comment by grumphus** [comment]
Ah I see the icons in the update. :) Makes more sense now. Thanks again!

EDIT: This has to be one of the best features ever. Thanks a lot! I can imagine this being an Electron limitation but if there was a way you can tile workspaces vertically or horizontally, that would be a killer feature.

But regardless, I suggest that feature should be highlighted on your homepage. Really useful feature and love the default icons for Work, School and Life.

**Pull request merged**
