### PR TITLE
Add option to ignore certificate errors

### LINKED ISSUE #595: feature: support custom certificate
# Feature Request
**Describe the Feature Request**

As discussed in https://github.com/atomery/webcatalog/issues/537#issuecomment-595093450

@maciesse

**Describe Preferred Solution**

**Describe Alternatives**

**Additional Context**

### LINKED ISSUE #782: feature: add option to ignore SSL error
> Hi, I have 2 questions/problems. - https://outlook.office.com/ or the build in outlook app does not keep the login ... displays a endless loading screen - Is there any way to ignore ssl errors? I've tried to make one for a intranet website, which uses ssl but without a valid certificate (displays a "This site can’t be reached.") Im using v20.3.1 Regards, Martin

### PR DESCRIPTION
**Pull request by quanglam2807**
Resolve #595 
Resolve #782

### CODE REVIEW

**Comment by eitch** [comment]
Am i blind, or where did this feature go to?

**Comment by quanglam2807** [comment]
Screen Shot 2020-12-07 at 5 38 37 PM

I admit there're too many options already. I'll try to add search to the prefs page.

**Comment by eitch** [comment]
Hi, but i don't have this:

image

I'm on the latest AppImage that i just downloaded today.

**Comment by quanglam2807** [comment]
Each app you install from WebCatalog has their own Preferences. The preferences you’re looking at is for WebCatalog.

**Comment by eitch** [comment]
Thanks. Now i found it.

**Comment by quanglam2807** [comment]
Great! I’ll try to improve the UI to make it clearer

**Pull request merged**
